title: Just the Docs Test Pages
description: Test pages for configurting Just The Docs to render Mermaid diagrams correctly
theme: just-the-docs
#
#  url: https://just-the-docs.github.io
#
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
#
# Mermaid configuration : Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
mermaid:
  version: "11.15.0"
